Create classes schema
luizppa/organizador-escolar pull request #4
Opened 2021-06-15 23:49 UTC by KaioAlex2018

2021-06-16 19:49 UTC, luizppa requested changes

2021-06-16 19:49 UTC, luizppa commented on organizador-escolar-backend/models/class-model.ts
> +function arrayLimit(val: string | any[]) {
Acho que a verificação que deveríamos fazer aqui deveria ser de quantidade mínima, e acho que faria mais sentido fazer ela no horário, então por exemplo, uma classe precisa ser registrada em pelo menos 1 horário.

2021-06-16 20:27 UTC, luizppa requested changes

2021-06-16 20:27 UTC, luizppa commented on organizador-escolar-backend/models/class-model.ts
> +    time: [{ type: Date, require: true}],
Talvez seja legal a gente colocar esses campos que são arrays com nomes no plural

2021-06-16 20:32 UTC, luizppa commented on organizador-escolar-backend/models/class-model.ts
> +export const User = mongoose.model('Class', classSchema);
Aqui estamos exportando o model de aula com o nome "User", deveria ser algo que remete a matéria, e talvez seria bom pensarmos em algo diferente de "Class" pra não ter nenhum conflito com a palavra reservada "class".

2021-06-17 02:17 UTC, KaioAlex2018 commented on organizador-escolar-backend/models/class-model.ts
> +function arrayLimit(val: string | any[]) {
Sim, faz mais sentido...

2021-06-17 02:18 UTC, KaioAlex2018 commented on organizador-escolar-backend/models/class-model.ts
> +    time: [{ type: Date, require: true}],
Mudei time para schedules e link para links.

2021-06-17 02:18 UTC, KaioAlex2018 commented on organizador-escolar-backend/models/class-model.ts
> +export const User = mongoose.model('Class', classSchema);
Troquei o "Class" por "Lesson", inclusive no nome do arquivo.

2021-06-17 12:01 UTC, luizppa approved these changes

2021-06-17 12:02 UTC, merged