Added link router and save_link implemented
luizppa/organizador-escolar pull request #5
Opened 2021-07-02 01:12 UTC by KaioAlex

2021-07-04 17:06 UTC, luizppa requested changes
Fiz duas observações pra gente discutir. Acho que também seria legal excluir os arquivos que colocamos em link-controller e no router de link, já que estamos usando a estrutura da aula mesmo, assim não duplicamos código.

2021-07-04 17:06 UTC, luizppa commented on organizador-escolar-backend/controllers/lesson-controller.ts
> +            lesson["links"] = `/lesson/${code}`;
Acho que aqui o ideal seria receber um link do corpo da requisição e adicionar ele nesse vetor de links, assim o usuário pode selecionar os links que ele relaciona a cada aula

2021-07-04 17:06 UTC, luizppa commented on organizador-escolar-backend/controllers/lesson-controller.ts
> +    async save(code: String) {
Acho que seria legal ter um nome mais descritivo nesse método, por exemplo "save_link"

2021-07-05 01:40 UTC, KaioAlex commented on organizador-escolar-backend/controllers/lesson-controller.ts
> +            lesson["links"] = `/lesson/${code}`;
saveLink recebe agora code e link

2021-07-05 01:43 UTC, luizppa approved these changes

2021-07-05 01:43 UTC, merged